export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";


export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const REGISTER_ENTITI_SUCCESS = "REGISTER_ENTITI_SUCCESS";
export const REGISTER_ENTITI_FAILURE = "REGISTER_ENTITI_FAILURE";
export const GET_CAMPAIGN_ID = "GET_CAMPAIGN_ID";
export const POST_CAMPAIGN = "POST_CAMPAIGN";
export const GET_CAMPAIGN = "GET_CAMPAIGN";
export const CREATE_CAMPAIGN_SUCCESS = "CREATE_CAMPAIGN_SUCCESS";
export const CREATE_CAMPAIGN_FAILURE = "CREATE_CAMPAIGN_FAILURE";
